security:
    client-id: ${CLIENT_ID:myclientid}
    jwt:
        secret: ${JWT_SECRET:mytokensecret}
        duration-in-seconds: ${JWT_DURATION_IN_SECONDS:86400}
spring:
    application:
        name: Authentication App
    profiles:
        active: dev
    jpa:
        open-in-view: false
