security:
    client-id: ${CLIENT_ID:myclientid}
    client-secret: ${CLIENT_SECRET:myclientsecret}
    jwt:
        duration-in-seconds: ${JWT_DURATION_IN_SECONDS:86400}
spring:
    application:
        name: Authentication App
    profiles:
        active: dev
    jpa:
        open-in-view: false
